import { build } from 'esbuild';
import { dirname, resolve } from 'node:path';
import { readFileSync, existsSync, writeFileSync } from 'node:fs';

export async function buildViewerMenu() {
  const result = await build({
    entryPoints: ['ui/viewer-menu.jsx'], outfile: 'extension/viewer-menu.js',
    bundle: true, format: 'esm', target: ['safari16.4'], minify: true, metafile: true,
    define: { 'process.env.NODE_ENV': '"production"' },
    banner: { js: '// Generated by scripts/build-ui.mjs. Edit ui/viewer-menu.jsx, then regenerate.' },
  });
  const packages = new Map();
  for (const input of Object.keys(result.metafile.inputs)) {
    if (!input.includes('node_modules')) continue;
    let folder = dirname(resolve(input));
    while (!existsSync(resolve(folder, 'package.json')) && dirname(folder) !== folder) folder = dirname(folder);
    if (!existsSync(resolve(folder, 'package.json'))) continue;
    const pkg = JSON.parse(readFileSync(resolve(folder, 'package.json'), 'utf8'));
    if (packages.has(pkg.name)) continue;
    const file = ['LICENSE','LICENSE.md','LICENSE.txt','license'].find(name => existsSync(resolve(folder,name)));
    packages.set(pkg.name, `${pkg.name}@${pkg.version} (${pkg.license || 'see package'})\n${file ? readFileSync(resolve(folder,file),'utf8') : pkg.repository?.url || ''}`);
  }
  writeFileSync('extension/THIRD_PARTY_NOTICES.txt', '// Generated by scripts/build-ui.mjs; do not edit.\n\n' + [...packages.values()].join('\n\n---\n\n'));
}
if (process.argv[1] && resolve(process.argv[1]) === resolve('scripts/build-ui.mjs')) await buildViewerMenu();
