import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';

export function configureNative(projectDirectory, legacy = false) {
  const signing = legacy ? { team: 'LEGACY0000', identity: '0'.repeat(40) } : JSON.parse(readFileSync(resolve('.local-signing.json'),'utf8'));
  if (!/^[A-Z0-9]{10}$/.test(signing.team) || !/^[A-F0-9]{40}$/.test(signing.identity)) throw new Error('Configure a stable local signing identity first.');
  const group = legacy ? 'legacy-export' : `${signing.team}.local.chatgpt.ImagesManager`;
  const base = join(projectDirectory,'ChatGPT Images Manager');
  const banner = '// Generated by scripts/native-project.mjs. Edit native/ sources instead.\n';
  const core = readFileSync(resolve('native/NativeStore.swift'),'utf8') + '\n' + readFileSync(resolve('native/NativeThumbnail.swift'),'utf8');
  const version = JSON.parse(readFileSync(resolve('extension/manifest.json'),'utf8')).version;
  writeFileSync(join(base,'ChatGPT Images Manager Extension/SafariWebExtensionHandler.swift'),banner + core + '\n' + readFileSync(resolve('native/SafariWebExtensionHandler.swift'),'utf8'));
  writeFileSync(join(base,'ChatGPT Images Manager/AppDelegate.swift'),banner + core + '\n' + readFileSync(resolve('native/LegacyImport.swift'),'utf8') + '\n' + readFileSync(resolve('native/AppDelegate.swift'),'utf8'));
  for (const target of ['ChatGPT Images Manager','ChatGPT Images Manager Extension']) {
    const path = join(base,target,'Info.plist');
    const source = readFileSync(path,'utf8').replace(/(<key>CFBundleShortVersionString<\/key>\s*<string>)[^<]*(<\/string>)/,`$1${version}$2`)
      .replace(/(<key>CFBundleVersion<\/key>\s*<string>)[^<]*(<\/string>)/,`$1${version}$2`);
    writeFileSync(path,source.replace(/<\/dict>\s*<\/plist>\s*$/,`<key>ImagesGroup</key><string>${group}</string>\n</dict>\n</plist>\n`));
  }
  const groups = legacy ? '' : `<key>com.apple.security.application-groups</key><array><string>${group}</string></array>`;
  writeFileSync(join(base,'Native.entitlements'),`<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0"><dict><key>com.apple.security.app-sandbox</key><true/><key>com.apple.security.network.client</key><true/><key>com.apple.security.files.user-selected.read-only</key><true/>${groups}</dict></plist>\n`);
  const path = join(base,'ChatGPT Images Manager.xcodeproj/project.pbxproj');
  const project = readFileSync(path,'utf8').replaceAll('CODE_SIGN_STYLE = Automatic;', 'CODE_SIGN_STYLE = Manual;\n\t\t\t\tCODE_SIGN_ENTITLEMENTS = Native.entitlements;').replaceAll('REGISTER_APP_GROUPS = YES;', 'REGISTER_APP_GROUPS = NO;')
    .replace(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${version};`)
    .replace(/CURRENT_PROJECT_VERSION = [^;]+;/g, `CURRENT_PROJECT_VERSION = ${version};`);
  writeFileSync(path,project);
}
