import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { mkdirSync, cpSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { buildSync } from 'esbuild';
const directory = resolve('build/safari');
mkdirSync(directory, { recursive: true });
const resources = resolve('build/safari-resources');
cpSync(resolve('extension'), resources, { recursive: true });
const manifest = JSON.parse(readFileSync(`${resources}/manifest.json`, 'utf8'));
delete manifest.background.type;
writeFileSync(`${resources}/manifest.json`, `${JSON.stringify(manifest, null, 2)}\n`);
buildSync({ entryPoints: ['extension/background.js'], bundle: true, format: 'iife', outfile: `${resources}/background.js`,
  banner: { js: '// Generated by scripts/safari.mjs. Change extension sources, then regenerate.' } });
const command = spawnSync('xcrun', ['safari-web-extension-converter', resources, '--project-location', directory,
  '--app-name', 'ChatGPT Images Manager', '--bundle-identifier', 'local.chatgpt.ChatGPT-Images-Manager', '--swift', '--macos-only', '--no-open', '--no-prompt',
  ...(existsSync(`${directory}/ChatGPT Images Manager/ChatGPT Images Manager.xcodeproj`) ? ['--force'] : [])], { stdio: 'inherit' });
process.exit(command.status || 0);
