import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { mkdirSync, cpSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { buildSync } from 'esbuild';
import { configureNative } from './native-project.mjs';
const legacy = process.argv.includes('--legacy-export');
const directory = resolve(legacy ? 'build/legacy-safari' : 'build/safari');
mkdirSync(directory, { recursive: true });
const resources = resolve(legacy ? 'build/legacy-resources' : 'build/safari-resources');
cpSync(resolve('extension'), resources, { recursive: true });
const manifest = JSON.parse(readFileSync(`${resources}/manifest.json`, 'utf8'));
if (legacy) {
  manifest.background = { service_worker: 'legacy-background.js' }; delete manifest.content_scripts;
  cpSync(resolve('native/legacy-export.html'), `${resources}/library.html`);
  cpSync(resolve('native/legacy-export.css'), `${resources}/legacy-export.css`);
  cpSync(resolve('native/legacy-export.js'), `${resources}/legacy-export.js`);
  cpSync(resolve('native/legacy-cleanup.js'), `${resources}/legacy-cleanup.js`);
  buildSync({ entryPoints: ['native/legacy-background.js'], bundle: true, format: 'iife', outfile: `${resources}/legacy-background.js`,
    banner: { js: '// Generated read-only legacy transfer. Change native sources, then regenerate.' } });
} else delete manifest.background.type;
writeFileSync(`${resources}/manifest.json`, `${JSON.stringify(manifest, null, 2)}\n`);
buildSync({ entryPoints: ['extension/background.js'], bundle: true, format: 'iife', outfile: `${resources}/background.js`,
  banner: { js: '// Generated by scripts/safari.mjs. Change extension sources, then regenerate.' } });
const command = spawnSync('xcrun', ['safari-web-extension-converter', resources, '--project-location', directory,
  '--app-name', 'ChatGPT Images Manager', '--bundle-identifier', 'local.chatgpt.ChatGPT-Images-Manager', '--swift', '--macos-only', '--no-open', '--no-prompt',
  ...(existsSync(`${directory}/ChatGPT Images Manager/ChatGPT Images Manager.xcodeproj`) ? ['--force'] : [])], { stdio: 'inherit' });
if (!command.status) configureNative(directory, legacy);
process.exit(command.status || 0);
